[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "npm run build:netlify --workspace=lunexa-clone"
  publish = "out"
  ignore_warnings = false

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXT_TELEMETRY_DISABLED = "1"

# Enable asset optimization but preserve Next.js optimizations
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false # Let Next.js handle CSS bundling
  minify = true

[build.processing.js]
  bundle = false # Let Next.js handle JS bundling
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Cache settings for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css"

[[headers]]
  for = "/_next/static/chunks/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript"

[[headers]]
  for = "/_next/static/media/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA routing - ensure all routes work correctly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

# Ensure all paths with trailing slashes work correctly
[[redirects]]
  from = "/*"
  to = ":splat/index.html"
  status = 200
  force = true
  conditions = {Path = {match = "\\/$"}}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Additional SPA routes with force=true for proper client-side routing
[[redirects]]
  from = "/blog/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/contact/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/login/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/signup/*"
  to = "/index.html"
  status = 200
  force = true